### ISSUE TITLE
Unable to load panel after update

### ISSUE THREAD

**Issue by 3Dxcub3** [jordanruthe/KlipperScreen#925] opened 2023-03-12 01:25 UTC
this error comes up on the Screen after a recent update:

Unable to load panel job_status Unable to create panel: job_status
'filament_diameter'
<img width="668" alt="Screen Shot 2023-03-11 at 21 24 15" src="https://user-images.githubusercontent.com/24828144/224519126-fd067e95-2f47-4976-9923-6de7e3991cba.png">

A solution/workaround for this error would be much appreciated.

**Comment by witem** [comment] 2023-03-12 10:28
The same for me

**Comment by alfrix** [comment] 2023-03-17 13:06
duplicate of #924

**Closed by alfrix** 2023-03-17 13:06 UTC
