### ISSUE TITLE
[FR] Additional Screen Timeout Duration when Klipper is in the SHUTDOWN State

### ISSUE THREAD

**Issue by dhenry437** [jordanruthe/KlipperScreen#945] opened 2023-04-05 03:51 UTC
**Is your feature request related to a problem? Please describe.**
No related problem.

**Describe the solution you'd like**
I utilise the Klipper SHUTDOWN state for my power management and would like to be able to keep the screen on when the printer and Klipper are on, but let the screen timeout when they are off. Also an added bonus would be a button to put the screen to sleep preferably on the printing panel, so in the case I run a print overnight I can blank the screen.

**Describe alternatives you've considered**
I think there may be a way to use the GCODE_SHELL_COMMAND extension to create a macro to blank the screen, and then add a button to the print panel for this macro? Let me know if I'm thinking straight or if this is a fools errand.

But as far as I've read in your docs I don't think there is a way to achieve the alternate screen timeouts through config.

**Comment by alfrix** [comment] 2023-05-14 04:43
duplicate of #311 and yes in the meantime you can use GCODE_SHELL_COMMAND and `xset dpms force off` and add the button using the menu system https://klipperscreen.readthedocs.io/en/latest/Configuration/#menu

**Closed by alfrix** 2023-05-14 04:43 UTC
