### ISSUE TITLE
[FR] Add Web UI access from display

### ISSUE THREAD

**Issue by Matszwe02** [jordanruthe/KlipperScreen#905] opened 2023-02-26 17:43 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes I need to go to my PC and access some settings that are not available on klipperscreen.

**Describe the solution you'd like**
Add "WebUI" button to open a popup which has a browser with opened localhost with selected port (default 80). It ultimately opens Mainsail, Fluidd or OctoPrint

**Describe alternatives you've considered**
Implementing a whole lot of functions in KlipperScreen (not as easy to implement)

**Additional context**

**Comment by hawkeyexp** [comment] 2023-03-11 20:42
Hm, does it make sense? Initial i think no - klipperscreen is an alternate control interface like mainsail fluid etc. - additional it is not really funny to control the web based interfaces on the small screens used on printers in most cases.

**Comment by Matszwe02** [comment] 2023-03-12 10:24
> Hm, does it make sense? Initial i think no - klipperscreen is an alternate control interface like mainsail fluid etc. - additional it is not really funny to control the web based interfaces on the small screens used on printers in most cases.

Right, but itself lacks many features. That webUI won't be for everyday use, just to control that one thing per month when you need for example to change pin in printer.cfg

**Comment by alfrix** [comment] 2023-05-14 04:51
duplicate of the idea in #682 the answer is: maybe

**Closed by alfrix** 2023-05-14 04:51 UTC
