### ISSUE TITLE
Actions panel blank from default - no sub menus

### ISSUE THREAD

**Issue by NiLMoXiE** [jordanruthe/KlipperScreen#849] opened 2022-12-13 22:24 UTC
This has been baffling me for the last hour - thought I was doing something wrong - from default settings the Actions panel is blank - looking at the defaults.conf there should be sub menus for 'move', 'extrude', 'fan', along with others if enabled but there's nothing - just a black screen. see attached.

I have tried adding a sub menu to the actions panel in klipperscreen.conf but nothing happens. I can add sub menus to anything else just not the Actions panel. Could there be a possible spelling mistake somewhere
![Klipperscreen Actions](https://user-images.githubusercontent.com/110064677/207457653-a3538970-50cb-4628-9ed4-1d55be6666fc.jpg)

**Comment by alfrix** [comment] 2022-12-13 22:31
already fixed it was caused because of the lack of name in the printer

duplicate of #838 and #843

**Closed by alfrix** 2022-12-13 22:31 UTC
