### ISSUE TITLE
[FR] Toolhead Z in printing panel

### ISSUE THREAD

**Issue by Zuendapp** [jordanruthe/KlipperScreen#809] opened 2022-11-24 13:26 UTC
Hello,

in my Ender 3 v2 with Fluidd and KlipperScreen there is no "live" Z-Value shown like in the Fluidd Webinterface.
There ist only the fixed layer hight of Z but not the live Z-Value with adjustments i.e. by a saved bed-mesh like in the Fluid Webinterface visible.
Is there any option to activate this?

Thank you very much!

BR

**Comment by alfrix** [comment] 2022-11-26 10:37
This is not a bug...
the printing panel z is from gcode, it's by design and not configurable at the moment
i was thinking on changing the secondary page that has XYZ to real tooolhead coordinates, so i will close this issue when that gets merged

**Closed** 2022-11-26 19:02 UTC

**Comment by Zuendapp** [comment] 2022-11-27 12:01
> This is not a bug...
> the printing panel z is from gcode, it's by design and not configurable at the moment
> i was thinking on changing the secondary page that has XYZ to real tooolhead coordinates, so i will close this issue when that gets merged

Perfect, thank you!
