### ISSUE TITLE
Z Calibrate Accept Button Does Nothing (Visually)

### ISSUE THREAD

**Issue by TehProgrammer** [jordanruthe/KlipperScreen#410] opened 2022-01-08 22:37 UTC
When using the Z Calibrate function in Klipperscreen, the Accept button does not dismiss the calibrate screen or show any messages.  I have confirmed that it saves the value, but there is no feedback on this.

**Comment by randellhodges** [comment] 2022-01-08 22:59
Duplicate of https://github.com/jordanruthe/KlipperScreen/issues/409?

**Closed** 2022-01-13 01:03 UTC
