### ISSUE TITLE
Add pressure advance slider [FR]

### ISSUE THREAD

**Issue by Matszwe02** [jordanruthe/KlipperScreen#938] opened 2023-03-29 13:22 UTC
**Is your feature request related to a problem? Please describe.**
I need to tune my pressure advance on the mainsail
**Describe the solution you'd like**
pressure advance slider somewhere in the menu (also during print)
**Describe alternatives you've considered**
stick to mainsail
**Additional context**

**Comment by alfrix** [comment] 2023-04-01 13:42
closing as duplicate of #724

**Closed** 2023-04-01 13:42 UTC
