### ISSUE TITLE
Require confirm on Emergency Stop

### ISSUE THREAD

**Issue by ckvsoft** [jordanruthe/KlipperScreen#341] opened 2021-11-25 21:04 UTC
Hallo
Feature Request
It would be nice that this feature, Require confirm on Emergency StopShow a confirmation dialog on Emergency Stop,
 like the new Mainsail (beta) has also been included in Klipperscreen. It hasn't happened to me in the first place that I accidentally reached the icon.

lg Chris

**Comment by alfrix** [comment] 2021-11-25 23:33
Duplicate of #321

**Closed** 2021-12-02 00:58 UTC
